# Generated by Django 3.2.9 on 2021-11-17 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("date_published", models.DateField()),
                (
                    "ISBN_number",
                    models.CharField(
                        max_length=13,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(13)],
                    ),
                ),
                ("page_number", models.PositiveIntegerField(null=True)),
                ("link_to_cover", models.URLField(null=True)),
                ("language", models.CharField(max_length=200)),
            ],
        ),
    ]
